-- 1 - 
SELECT *
FROM LIVROS;

INSERT INTO LIVROS
VALUES( NULL, 'As Cônicas de Nárnia', 'CS Lewis', 1950, 1, 'Fantasia', '978-0064471190', 'HarperCollins', 768, 'Inglês' );

-- 2 -
UPDATE LIVROS
SET DISPONIVEL = FALSE
WHERE 	ANO_PUBLICACAO < 2000;

-- 3 -
UPDATE LIVROS
SET EDITORA = 'Plume Books'
WHERE TITULO = '1984';

-- 4 -
DELETE FROM LIVROS WHERE IDIOMA = 'Francês' AND ANO_PUBLICACAO > 1970;

-- 5 -
SELECT *
FROM LIVROS
WHERE QUANTIDADE_PAGINAS > 500;

-- 6 -
SELECT 	CATEGORIA,
		COUNT(*)
FROM LIVROS
GROUP BY CATEGORIA;

-- 7 -
SELECT *
FROM LIVROS
LIMIT 5;

-- 8 -
SELECT AVG(ANO_PUBLICACAO)
FROM LIVROS;

-- 9 -
SELECT *
FROM LIVROS
ORDER BY ANO_PUBLICACAO DESC;

-- 10 -
SELECT *
FROM LIVROS
WHERE	TITULO LIKE 'A%' AND
	ANO_PUBLICACAO BETWEEN 1980 AND 2000;
